// ISO 3116-2 country codes
export enum Country { // eslint-disable-line no-restricted-syntax
  AD = 'Andorra',
  AE = 'United Arab Emirates',
  AF = 'Afghanistan',
  AG = 'Antigua and Barbuda',
  AI = 'Anguilla',
  AL = 'Albania',
  AM = 'Armenia',
  AN = 'Netherlands Antilles',
  AO = 'Angola',
  AQ = 'Antarctica',
  AR = 'Argentina',
  AS = 'American Samoa',
  AT = 'Austria',
  AU = 'Australia',
  AW = 'Aruba',
  AX = 'Åland Islands',
  AZ = 'Azerbaijan',
  BA = 'Bosnia and Herzegovina',
  BB = 'Barbados',
  BD = 'Bangladesh',
  BE = 'Belgium',
  BF = 'Burkina Faso',
  BG = 'Bulgaria',
  BH = 'Bahrain',
  BI = 'Burundi',
  BJ = 'Benin',
  BL = 'Saint Barthélemy',
  BM = 'Bermuda',
  BN = 'Brunei Darussalam',
  BO = 'Bolivia',
  BR = 'Brazil',
  BS = 'Bahamas',
  BT = 'Bhutan',
  BV = 'Bouvet Island',
  BW = 'Botswana',
  BY = 'Belarus',
  BZ = 'Belize',
  CA = 'Canada',
  CC = 'Cocos Islands',
  CD = 'Democratic Republic of the Congo',
  CF = 'Central African Republic',
  CG = 'Republic of the Congo',
  CH = 'Switzerland',
  CI = "Côte d'Ivoire",
  CK = 'Cook Islands',
  CL = 'Chile',
  CM = 'Cameroon',
  CN = 'China',
  CO = 'Colombia',
  CR = 'Costa Rica',
  CU = 'Cuba',
  CV = 'Cape Verde',
  CW = 'Curaçao',
  CX = 'Christmas Island',
  CY = 'Cyprus',
  CZ = 'Czechia',
  DE = 'Germany',
  DJ = 'Djibouti',
  DK = 'Denmark',
  DM = 'Dominica',
  DO = 'Dominican Republic',
  DZ = 'Algeria',
  EC = 'Ecuador',
  EE = 'Estonia',
  EG = 'Egypt',
  EH = 'Western Sahara',
  ER = 'Eritrea',
  ES = 'Spain',
  ET = 'Ethiopia',
  FI = 'Finland',
  FJ = 'Fiji',
  FK = 'Falkland Islands',
  FM = 'Micronesia',
  FO = 'Faroe Islands',
  FR = 'France',
  GA = 'Gabon',
  GB = 'United Kingdom',
  GD = 'Grenada',
  GE = 'Georgia',
  GF = 'French Guiana',
  GG = 'Guernsey',
  GH = 'Ghana',
  GI = 'Gibraltar',
  GL = 'Greenland',
  GM = 'Gambia',
  GN = 'Guinea',
  GP = 'Guadeloupe',
  GQ = 'Equatorial Guinea',
  GR = 'Greece',
  GS = 'South Georgia',
  GT = 'Guatemala',
  GU = 'Guam',
  GW = 'Guinea-Bissau',
  GY = 'Guyana',
  HK = 'Hong Kong',
  HM = 'Heard Island and McDonald Islands',
  HN = 'Honduras',
  HR = 'Croatia',
  HT = 'Haiti',
  HU = 'Hungary',
  ID = 'Indonesia',
  IE = 'Ireland',
  IL = 'Israel',
  IM = 'Isle Of Man',
  IN = 'India',
  IO = 'Indian Ocean',
  IQ = 'Iraq',
  IR = 'Iran',
  IS = 'Iceland',
  IT = 'Italy',
  JE = 'Jersey',
  JM = 'Jamaica',
  JO = 'Jordan',
  JP = 'Japan',
  KE = 'Kenya',
  KG = 'Kyrgyzstan',
  KH = 'Cambodia',
  KI = 'Kiribati',
  KM = 'Comoros',
  KN = 'Saint Kitts and Nevis',
  KP = 'North Korea',
  KR = 'South Korea',
  KW = 'Kuwait',
  KY = 'Cayman Islands',
  KZ = 'Kazakhstan',
  LA = "Lao People's Democratic Republic",
  LB = 'Lebanon',
  LC = 'Saint Lucia',
  LI = 'Liechtenstein',
  LK = 'Sri Lanka',
  LR = 'Liberia',
  LS = 'Lesotho',
  LT = 'Lithuania',
  LU = 'Luxembourg',
  LV = 'Latvia',
  LY = 'Libyan Arab Jamahiriya',
  MA = 'Morocco',
  MC = 'Monaco',
  MD = 'Moldova',
  ME = 'Montenegro',
  MF = 'Saint Martin',
  MG = 'Madagascar',
  MH = 'Marshall Islands',
  MK = 'Macedonia',
  ML = 'Mali',
  MM = 'Myanmar',
  MN = 'Mongolia',
  MO = 'Macao',
  MP = 'Northern Mariana Islands',
  MQ = 'Martinique',
  MR = 'Mauritania',
  MS = 'Montserrat',
  MT = 'Malta',
  MU = 'Mauritius',
  MV = 'Maldives',
  MW = 'Malawi',
  MX = 'Mexico',
  MY = 'Malaysia',
  MZ = 'Mozambique',
  NA = 'Namibia',
  NC = 'New Caledonia',
  NE = 'Niger',
  NF = 'Norfolk Island',
  NG = 'Nigeria',
  NI = 'Nicaragua',
  NL = 'Netherlands',
  NO = 'Norway',
  NP = 'Nepal',
  NR = 'Nauru',
  NU = 'Niue',
  NZ = 'New Zealand',
  OM = 'Oman',
  PA = 'Panama',
  PE = 'Peru',
  PF = 'French Polynesia',
  PG = 'Papua New Guinea',
  PH = 'Philippines',
  PK = 'Pakistan',
  PL = 'Poland',
  PM = 'Saint Pierre and Miquelon',
  PN = 'Pitcairn Islands',
  PR = 'Puerto Rico',
  PS = 'Palestinian Territory',
  PT = 'Portugal',
  PW = 'Palau',
  PY = 'Paraguay',
  QA = 'Qatar',
  RE = 'Réunion',
  RO = 'Romania',
  RS = 'Serbia',
  RU = 'Russian Federation',
  RW = 'Rwanda',
  SA = 'Saudi Arabia',
  SB = 'Solomon Islands',
  SC = 'Seychelles',
  SD = 'Sudan',
  SE = 'Sweden',
  SG = 'Singapore',
  SH = 'Saint Helena',
  SI = 'Slovenia',
  SJ = 'Svalbard and Jan Mayen',
  SK = 'Slovakia',
  SL = 'Sierra Leone',
  SM = 'San Marino',
  SN = 'Senegal',
  SO = 'Somalia',
  SR = 'Suriname',
  SS = 'South Sudan',
  ST = 'São Tomé and Príncipe',
  SV = 'El Salvador',
  SY = 'Syrian Arab Republic',
  SZ = 'Swaziland',
  TC = 'Turks and Caicos Islands',
  TD = 'Chad',
  TF = 'French Southern Territories',
  TG = 'Togo',
  TH = 'Thailand',
  TI = 'Tibet', // Suggested ISO country code, non-official
  TJ = 'Tajikistan',
  TK = 'Tokelau',
  TL = 'Timor-Leste',
  TM = 'Turkmenistan',
  TN = 'Tunisia',
  TO = 'Tonga',
  TR = 'Turkey',
  TT = 'Trinidad and Tobago',
  TV = 'Tuvalu',
  TW = 'Taiwan',
  TZ = 'Tanzania',
  UA = 'Ukraine',
  UG = 'Uganda',
  UM = 'U.S. Territory',
  US = 'United States',
  UY = 'Uruguay',
  UZ = 'Uzbekistan',
  VA = 'Vatican City',
  VC = 'Saint Vincent',
  VE = 'Venezuela',
  VG = 'British Virgin Islands',
  VI = 'U.S. Virgin Islands',
  VN = 'Viet Nam',
  VU = 'Vanuatu',
  WF = 'Wallis and Futuna',
  WS = 'Samoa',
  XK = 'Kosovo', // Temporary recognized country code until ISO officially assigns code
  YE = 'Yemen',
  YT = 'Mayotte',
  ZA = 'South Africa',
  ZM = 'Zambia',
  ZW = 'Zimbabwe',
}

export const countryDialCodes: Record<Country, string> = {
  [Country.AF]: '+93',
  [Country.AL]: '+355',
  [Country.AX]: '+358',
  [Country.DZ]: '+213',
  [Country.AS]: '+1 684',
  [Country.AD]: '+376',
  [Country.AO]: '+244',
  [Country.AI]: '+1 264',
  [Country.AQ]: '+672',
  [Country.AG]: '+1 268',
  [Country.AR]: '+54',
  [Country.AM]: '+374',
  [Country.AW]: '+297',
  [Country.AU]: '+61',
  [Country.AT]: '+43',
  [Country.AZ]: '+994',
  [Country.BS]: '+1 242',
  [Country.BH]: '+973',
  [Country.BD]: '+880',
  [Country.BB]: '+1 246',
  [Country.BY]: '+375',
  [Country.BE]: '+32',
  [Country.BZ]: '+501',
  [Country.BJ]: '+229',
  [Country.BM]: '+1 441',
  [Country.BT]: '+975',
  [Country.BV]: '+55',
  [Country.BO]: '+591',
  [Country.BA]: '+387',
  [Country.BW]: '+267',
  [Country.BR]: '+55',
  [Country.VG]: '+1 284',
  [Country.BN]: '+673',
  [Country.BG]: '+359',
  [Country.BF]: '+226',
  [Country.MM]: '+95',
  [Country.BI]: '+257',
  [Country.KH]: '+855',
  [Country.CM]: '+237',
  [Country.CA]: '+1',
  [Country.CV]: '+238',
  [Country.KY]: '+1 345',
  [Country.CF]: '+236',
  [Country.TD]: '+235',
  [Country.CL]: '+56',
  [Country.CN]: '+86',
  [Country.CX]: '+61',
  [Country.CC]: '+61',
  [Country.CO]: '+57',
  [Country.KM]: '+269',
  [Country.CK]: '+682',
  [Country.CR]: '+506',
  [Country.HR]: '+385',
  [Country.CU]: '+53',
  [Country.CW]: '+599',
  [Country.CY]: '+357',
  [Country.CZ]: '+420',
  [Country.CD]: '+243',
  [Country.DK]: '+45',
  [Country.DJ]: '+253',
  [Country.DM]: '+1 767',
  [Country.DO]: '+1 809',
  [Country.EC]: '+593',
  [Country.EG]: '+20',
  [Country.EH]: '+212',
  [Country.SV]: '+503',
  [Country.GQ]: '+240',
  [Country.ER]: '+291',
  [Country.EE]: '+372',
  [Country.ET]: '+251',
  [Country.FK]: '+500',
  [Country.FO]: '+298',
  [Country.FJ]: '+679',
  [Country.FI]: '+358',
  [Country.FR]: '+33',
  [Country.PF]: '+689',
  [Country.GA]: '+241',
  [Country.GM]: '+220',
  [Country.GE]: '+995',
  [Country.GF]: '+594',
  [Country.GG]: '+44',
  [Country.DE]: '+49',
  [Country.GH]: '+233',
  [Country.GI]: '+350',
  [Country.GR]: '+30',
  [Country.GS]: '+500',
  [Country.GL]: '+299',
  [Country.GD]: '+1 473',
  [Country.GU]: '+1 671',
  [Country.GT]: '+502',
  [Country.GN]: '+224',
  [Country.GP]: '+590',
  [Country.GW]: '+245',
  [Country.GY]: '+592',
  [Country.HT]: '+509',
  [Country.VA]: '+39',
  [Country.HN]: '+504',
  [Country.HK]: '+852',
  [Country.HM]: '+672',
  [Country.HU]: '+36',
  [Country.IS]: '+354',
  [Country.IN]: '+91',
  [Country.IO]: '+246',
  [Country.ID]: '+62',
  [Country.IR]: '+98',
  [Country.IQ]: '+964',
  [Country.IE]: '+353',
  [Country.IM]: '+44',
  [Country.IL]: '+972',
  [Country.IT]: '+39',
  [Country.JE]: '+44',
  [Country.CI]: '+225',
  [Country.JM]: '+1 876',
  [Country.JP]: '+81',
  [Country.JO]: '+962',
  [Country.KZ]: '+7',
  [Country.KE]: '+254',
  [Country.KI]: '+686',
  [Country.KW]: '+965',
  [Country.KG]: '+996',
  [Country.LA]: '+856',
  [Country.LV]: '+371',
  [Country.LB]: '+961',
  [Country.LS]: '+266',
  [Country.LR]: '+231',
  [Country.LY]: '+218',
  [Country.LI]: '+423',
  [Country.LT]: '+370',
  [Country.LU]: '+352',
  [Country.MO]: '+853',
  [Country.MK]: '+389',
  [Country.MG]: '+261',
  [Country.MW]: '+265',
  [Country.MY]: '+60',
  [Country.MV]: '+960',
  [Country.ML]: '+223',
  [Country.MT]: '+356',
  [Country.MH]: '+692',
  [Country.MR]: '+222',
  [Country.MU]: '+230',
  [Country.YT]: '+262',
  [Country.MX]: '+52',
  [Country.FM]: '+691',
  [Country.MD]: '+373',
  [Country.MC]: '+377',
  [Country.MN]: '+976',
  [Country.ME]: '+382',
  [Country.MS]: '+1 664',
  [Country.MA]: '+212',
  [Country.MZ]: '+258',
  [Country.NA]: '+264',
  [Country.NR]: '+674',
  [Country.NP]: '+977',
  [Country.NL]: '+31',
  [Country.AN]: '+599',
  [Country.NC]: '+687',
  [Country.NZ]: '+64',
  [Country.NI]: '+505',
  [Country.NE]: '+227',
  [Country.NG]: '+234',
  [Country.NU]: '+683',
  [Country.KP]: '+850',
  [Country.MP]: '+1 670',
  [Country.NO]: '+47',
  [Country.OM]: '+968',
  [Country.PK]: '+92',
  [Country.PW]: '+680',
  [Country.PA]: '+507',
  [Country.PG]: '+675',
  [Country.PY]: '+595',
  [Country.PE]: '+51',
  [Country.PH]: '+63',
  [Country.PN]: '+870',
  [Country.PL]: '+48',
  [Country.PT]: '+351',
  [Country.PR]: '+1',
  [Country.QA]: '+974',
  [Country.CG]: '+242',
  [Country.RO]: '+40',
  [Country.RU]: '+7',
  [Country.RW]: '+250',
  [Country.BL]: '+590',
  [Country.SH]: '+290',
  [Country.KN]: '+1 869',
  [Country.LC]: '+1 758',
  [Country.MF]: '+1 599',
  [Country.PM]: '+508',
  [Country.VC]: '+1 784',
  [Country.WS]: '+685',
  [Country.SM]: '+378',
  [Country.ST]: '+239',
  [Country.SA]: '+966',
  [Country.SN]: '+221',
  [Country.RS]: '+381',
  [Country.SC]: '+248',
  [Country.SL]: '+232',
  [Country.SG]: '+65',
  [Country.SK]: '+421',
  [Country.SI]: '+386',
  [Country.SB]: '+677',
  [Country.SO]: '+252',
  [Country.ZA]: '+27',
  [Country.KR]: '+82',
  [Country.ES]: '+34',
  [Country.LK]: '+94',
  [Country.SD]: '+249',
  [Country.SR]: '+597',
  [Country.SZ]: '+268',
  [Country.SE]: '+46',
  [Country.CH]: '+41',
  [Country.SY]: '+963',
  [Country.TW]: '+886',
  [Country.TJ]: '+992',
  [Country.TZ]: '+255',
  [Country.TH]: '+66',
  [Country.TL]: '+670',
  [Country.TG]: '+228',
  [Country.TK]: '+690',
  [Country.TO]: '+676',
  [Country.TT]: '+1 868',
  [Country.TN]: '+216',
  [Country.TR]: '+90',
  [Country.TM]: '+993',
  [Country.TC]: '+1 649',
  [Country.TV]: '+688',
  [Country.UG]: '+256',
  [Country.UA]: '+380',
  [Country.AE]: '+971',
  [Country.GB]: '+44',
  [Country.US]: '+1',
  [Country.UY]: '+598',
  [Country.VI]: '+1 340',
  [Country.UZ]: '+998',
  [Country.VU]: '+678',
  [Country.VE]: '+58',
  [Country.VN]: '+84',
  [Country.WF]: '+681',
  [Country.YE]: '+967',
  [Country.ZM]: '+260',
  [Country.ZW]: '+263',
  [Country.MQ]: '+596',
  [Country.NF]: '+672',
  [Country.PS]: '+970',
  [Country.RE]: '+262',
  [Country.SJ]: '+47',
  [Country.SS]: '+211',
  [Country.TF]: '+262',
  [Country.TI]: '+86',
  [Country.UM]: '+1',
  [Country.XK]: '+383',
};

export const countriesWithPostalCodes: (keyof typeof Country)[] = [
  'AD',
  'AF',
  'AI',
  'AL',
  'AM',
  'AR',
  'AS',
  'AT',
  'AU',
  'AZ',
  'BA',
  'BB',
  'BD',
  'BE',
  'BG',
  'BH',
  'BM',
  'BN',
  'BO',
  'BR',
  'BT',
  'BY',
  'CA',
  'CC',
  'CH',
  'CL',
  'CN',
  'CO',
  'CR',
  'CV',
  'CX',
  'CY',
  'CZ',
  'DE',
  'DK',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'ES',
  'ET',
  'FI',
  'FK',
  'FM',
  'FO',
  'FR',
  'GA',
  'GB',
  'GE',
  'GF',
  'GG',
  'GI',
  'GL',
  'GP',
  'GR',
  'GS',
  'GT',
  'GU',
  'GW',
  'HM',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IM',
  'IN',
  'IO',
  'IQ',
  'IS',
  'IT',
  'JE',
  'JM',
  'JO',
  'JP',
  'KE',
  'KG',
  'KH',
  'KR',
  'KW',
  'KY',
  'KZ',
  'LA',
  'LB',
  'LI',
  'LK',
  'LR',
  'LS',
  'LT',
  'LU',
  'LV',
  'LY',
  'MA',
  'MC',
  'MD',
  'ME',
  'MG',
  'MH',
  'MK',
  'MM',
  'MN',
  'MP',
  'MQ',
  'MT',
  'MV',
  'MX',
  'MY',
  'MZ',
  'NA',
  'NC',
  'NE',
  'NF',
  'NG',
  'NI',
  'NL',
  'NO',
  'NP',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PF',
  'PG',
  'PH',
  'PK',
  'PL',
  'PM',
  'PN',
  'PR',
  'PS',
  'PT',
  'PW',
  'PY',
  'RE',
  'RO',
  'RS',
  'RU',
  'SA',
  'SE',
  'SG',
  'SH',
  'SI',
  'SK',
  'SM',
  'SN',
  'SV',
  'SZ',
  'TC',
  'TD',
  'TH',
  'TJ',
  'TM',
  'TN',
  'TR',
  'TT',
  'TW',
  'UA',
  'UM',
  'US',
  'UY',
  'UZ',
  'VA',
  'VC',
  'VE',
  'VG',
  'VI',
  'VN',
  'WF',
  'WS',
  'XK',
  'YT',
  'ZA',
  'ZM',
];
